# Generated by Django 3.2 on 2022-02-04 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0002_intake_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='studnent',
            name='trackId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='affairs.track'),
            preserve_default=False,
        ),
    ]
