# Generated by Django 3.2 on 2022-02-04 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0003_studnent_trackid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studnent',
            old_name='trackId',
            new_name='track',
        ),
    ]
