# Generated by Django 3.2 on 2022-02-04 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0004_rename_trackid_studnent_track'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='studnent',
            new_name='student',
        ),
    ]
