# Generated by Django 3.2 on 2022-02-07 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0006_alter_student_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='affairs.track'),
        ),
    ]
